[openai]
api_key = "sk-xYBWXr1epqP3Uq1A05qUql9tAyBsJE5F8PL5L66gBaE328VG"

[redpill]
api_key = "sk-xYBWXr1epqP3Uq1A05qUql9tAyBsJE5F8PL5L66gBaE328VG"
api_url = "https://api.redpill.ai/v1/chat/completions"
model = "mistralai/ministral-8b"
